[package]
name = "multitoken_forge"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
erc1155 = { local = "../erc1155", rev = "devnet" }

[addresses]
multitoken_forge =  "0x0"
sui =  "0000000000000000000000000000000000000002"
erc1155 =  "0x0"
